name: SkyWarsForPE
main: larryTheCoder\SkyWarsAPI
version: "1.8_BETA"
api: [2.0.0]
author: larryTheCoder
commands:
  sw:
    description: use /qsg help for all parameters
    aliases: sk,skywars
permission:
  qsg.command.lobby:
    description: back to main lobby
    default: true
  qsg.acces:
    description: access the game intrance
    default: true
# For VIP access NOT DONE
#  sw.acces.full:
#    description: ability to join full game
#    default: true
  qsg.editlobby:
    description: prevent players from edit lobby
    default: op
  qsg.sign:
    description: join using signs 
    default: true
  qsg.command:
    description: allow player to use all qsg command
    default: op
    children:
     qsg.command.help:
        description: get QSG help menu
        default: op
     qsg.command.setlobby:
        description: set QSG main lobby
        default: op
     qsg.command.create:
        description: create a QSG arenas
        default: op
     qsg.command.reload:
        description: reload skywars plugin
        default: op
